FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /dashboard

# System dependencies for XGBoost and Evidently
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies first (layer caching)
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app.py .
COPY monitor_drift.py .

# Copy model artefacts (generated on Kaggle)
COPY fraud_model.joblib .
COPY feature_columns.joblib .

# Copy monitoring datasets (generated by generate_monitoring_data.py)
COPY train_baseline.csv .
COPY production_logs.csv .

EXPOSE 10000

CMD ["sh", "-c", "uvicorn app:app --host 0.0.0.0 --port ${PORT:-10000} --workers 2"]
